import {
  AcademicYear,
  ActivityLog,
  AttendanceRecord,
  Curriculum,
  Lesson,
  NotificationItem,
  Parent,
  Principal,
  Profile,
  School,
  SchoolClass,
  Student,
  Subject,
  Teacher,
  TopicProgress,
} from '../types';

export const initialSchools: School[] = [
  {
    id: 'sch-1',
    name: 'Özel Akademi Koleji — Beşiktaş Ana Kampüs',
    code: 'AKD-BES-01',
    city: 'İstanbul',
    district: 'Beşiktaş',
    address: 'Yıldız Mah. Çırağan Cad. No: 44, Beşiktaş',
    phone: '0212 258 0001',
    email: 'besiktas@akademipro.k12.tr',
    principal_id: 'prof-mudur',
    principal_name: 'Dr. Selim Karahan',
    student_count: 20,
    teacher_count: 3,
    class_count: 2,
    capacity: 250,
    status: 'aktif',
    created_at: '2026-08-01',
  },
  {
    id: 'sch-2',
    name: 'Özel Akademi Koleji — Kadıköy Kampüsü',
    code: 'AKD-KDK-02',
    city: 'İstanbul',
    district: 'Kadıköy',
    address: 'Moda Cad. Şair Nefi Sok. No: 12, Kadıköy',
    phone: '0216 345 0002',
    email: 'kadikoy@akademipro.k12.tr',
    principal_id: 'prof-mudur-2',
    principal_name: 'Gülşen Özdemir',
    student_count: 45,
    teacher_count: 6,
    class_count: 4,
    capacity: 300,
    status: 'aktif',
    created_at: '2026-08-10',
  },
  {
    id: 'sch-3',
    name: 'Özel Akademi Koleji — Çankaya Kampüsü',
    code: 'AKD-ANK-03',
    city: 'Ankara',
    district: 'Çankaya',
    address: 'Gaziosmanpaşa Mah. Filistin Sok. No: 28, Çankaya',
    phone: '0312 444 0003',
    email: 'cankaya@akademipro.k12.tr',
    principal_id: undefined,
    principal_name: undefined,
    student_count: 0,
    teacher_count: 0,
    class_count: 0,
    capacity: 200,
    status: 'aktif',
    created_at: '2026-09-01',
  },
];

export const initialPrincipals: Principal[] = [
  {
    id: 'prn-1',
    profile_id: 'prof-mudur',
    full_name: 'Dr. Selim Karahan',
    email: 'selim.mudur@akademipro.k12.tr',
    phone: '0532 111 2233',
    title: 'Okul Müdürü',
    assigned_school_id: 'sch-1',
    assigned_school_name: 'Özel Akademi Koleji — Beşiktaş Ana Kampüs',
    hire_date: '2023-08-15',
    status: 'aktif',
  },
  {
    id: 'prn-2',
    profile_id: 'prof-mudur-2',
    full_name: 'Gülşen Özdemir',
    email: 'gulsen.mudur@akademipro.k12.tr',
    phone: '0532 111 4455',
    title: 'Okul Müdürü',
    assigned_school_id: 'sch-2',
    assigned_school_name: 'Özel Akademi Koleji — Kadıköy Kampüsü',
    hire_date: '2024-07-01',
    status: 'aktif',
  },
  {
    id: 'prn-3',
    profile_id: 'prof-mudur-3',
    full_name: 'Murat Erkin',
    email: 'murat.erkin@akademipro.k12.tr',
    phone: '0532 111 7788',
    title: 'Kurucu Temsilcisi / Müdür',
    assigned_school_id: undefined,
    assigned_school_name: undefined,
    hire_date: '2025-06-15',
    status: 'aktif',
  },
];

export const initialAcademicYears: AcademicYear[] = [
  {
    id: 'ay-2026-2027',
    name: '2026-2027',
    start_date: '2026-09-07',
    end_date: '2027-06-18',
    is_active: true,
    is_archived: false,
  },
  {
    id: 'ay-2025-2026',
    name: '2025-2026',
    start_date: '2025-09-08',
    end_date: '2026-06-19',
    is_active: false,
    is_archived: true,
  },
];

export const initialProfiles: Profile[] = [
  {
    id: 'prof-bolge',
    role: 'bolge_sorumlusu',
    full_name: 'Kemal Sunar (Bölge Sorumlusu)',
    email: 'kemal.bolge@akademipro.k12.tr',
    phone: '0532 999 8877',
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    created_at: '2026-07-15',
  },
  {
    id: 'prof-mudur',
    role: 'mudur',
    full_name: 'Dr. Selim Karahan',
    email: 'selim.mudur@akademipro.k12.tr',
    phone: '0532 111 2233',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    created_at: '2026-08-01',
  },
  {
    id: 'prof-mudur-2',
    role: 'mudur',
    full_name: 'Gülşen Özdemir',
    email: 'gulsen.mudur@akademipro.k12.tr',
    phone: '0532 111 4455',
    avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
    created_at: '2026-08-01',
  },
  {
    id: 'prof-teacher-1',
    role: 'ogretmen',
    full_name: 'Ayşe Yılmaz',
    email: 'ayse.yilmaz@akademipro.k12.tr',
    phone: '0532 222 3344',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    created_at: '2026-08-05',
  },
  {
    id: 'prof-teacher-2',
    role: 'ogretmen',
    full_name: 'Mehmet Demir',
    email: 'mehmet.demir@akademipro.k12.tr',
    phone: '0532 333 4455',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    created_at: '2026-08-05',
  },
  {
    id: 'prof-teacher-3',
    role: 'ogretmen',
    full_name: 'Zeynep Aksoy',
    email: 'zeynep.aksoy@akademipro.k12.tr',
    phone: '0532 444 5566',
    avatar_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
    created_at: '2026-08-10',
  },
  {
    id: 'prof-parent-1',
    role: 'veli',
    full_name: 'Mustafa Çelik',
    email: 'mustafa.celik@gmail.com',
    phone: '0533 555 6677',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    created_at: '2026-08-15',
  },
  {
    id: 'prof-student-1',
    role: 'ogrenci',
    full_name: 'Kerem Çelik',
    email: 'kerem.celik@ogrenci.akademipro.k12.tr',
    phone: '0534 666 7788',
    avatar_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150',
    created_at: '2026-08-20',
  },
];

export const initialClasses: SchoolClass[] = [
  {
    id: 'cls-8a',
    name: '8-A',
    grade_level: 8,
    section: 'A',
    academic_year_id: 'ay-2026-2027',
    class_teacher_id: 'prof-teacher-1',
    class_teacher_name: 'Ayşe Yılmaz (Matematik)',
    capacity: 22,
    student_count: 10,
    attendance_rate: 94.6,
    is_active: true,
  },
  {
    id: 'cls-8b',
    name: '8-B',
    grade_level: 8,
    section: 'B',
    academic_year_id: 'ay-2026-2027',
    class_teacher_id: 'prof-teacher-2',
    class_teacher_name: 'Mehmet Demir (Fen Bilimleri)',
    capacity: 22,
    student_count: 10,
    attendance_rate: 91.2,
    is_active: true,
  },
  {
    id: 'cls-7a',
    name: '7-A',
    grade_level: 7,
    section: 'A',
    academic_year_id: 'ay-2026-2027',
    class_teacher_id: 'prof-teacher-3',
    class_teacher_name: 'Zeynep Aksoy (Türkçe)',
    capacity: 20,
    student_count: 0,
    attendance_rate: 96.0,
    is_active: true,
  },
];

export const initialTeachers: Teacher[] = [
  {
    id: 'teach-1',
    profile_id: 'prof-teacher-1',
    full_name: 'Ayşe Yılmaz',
    email: 'ayse.yilmaz@akademipro.k12.tr',
    phone: '0532 222 3344',
    branch: 'Matematik',
    status: 'aktif',
    hire_date: '2023-09-01',
    assigned_class_ids: ['cls-8a', 'cls-8b'],
  },
  {
    id: 'teach-2',
    profile_id: 'prof-teacher-2',
    full_name: 'Mehmet Demir',
    email: 'mehmet.demir@akademipro.k12.tr',
    phone: '0532 333 4455',
    branch: 'Fen Bilimleri',
    status: 'aktif',
    hire_date: '2024-02-15',
    assigned_class_ids: ['cls-8a', 'cls-8b', 'cls-7a'],
  },
  {
    id: 'teach-3',
    profile_id: 'prof-teacher-3',
    full_name: 'Zeynep Aksoy',
    email: 'zeynep.aksoy@akademipro.k12.tr',
    phone: '0532 444 5566',
    branch: 'Türkçe',
    status: 'aktif',
    hire_date: '2022-09-01',
    assigned_class_ids: ['cls-8a', 'cls-8b', 'cls-7a'],
  },
];

export const initialParents: Parent[] = [
  {
    id: 'par-1',
    profile_id: 'prof-parent-1',
    full_name: 'Mustafa Çelik',
    phone: '0533 555 6677',
    email: 'mustafa.celik@gmail.com',
    occupation: 'Makine Mühendisi',
    student_ids: ['stu-801', 'stu-811'], // 2 Çocuk: Kerem (8-A) & Defne (8-B)
  },
  {
    id: 'par-2',
    profile_id: 'prof-parent-2',
    full_name: 'Fatma Şahin',
    phone: '0533 444 7788',
    email: 'fatma.sahin@gmail.com',
    occupation: 'Mimar',
    student_ids: ['stu-802'],
  },
  {
    id: 'par-3',
    profile_id: 'prof-parent-3',
    full_name: 'Ali Öztürk',
    phone: '0533 222 9900',
    email: 'ali.ozturk@gmail.com',
    occupation: 'Avukat',
    student_ids: ['stu-803'],
  },
];

export const initialStudents: Student[] = [
  // 8-A Öğrencileri
  {
    id: 'stu-801',
    profile_id: 'prof-student-1',
    student_number: '801',
    first_name: 'Kerem',
    last_name: 'Çelik',
    birth_date: '2012-04-12',
    gender: 'Erkek',
    education_type: 'gunduzlu',
    class_id: 'cls-8a',
    class_name: '8-A',
    status: 'aktif',
    registration_date: '2026-08-20',
    parent_id: 'par-1',
    parent_name: 'Mustafa Çelik',
    parent_phone: '0533 555 6677',
    parent_email: 'mustafa.celik@gmail.com',
    parent_relation: 'Baba',
    attendance_rate: 96.0,
    curriculum_rate: 82.0,
    absenteeism_count: 1,
    late_count: 0,
    excused_count: 1,
    risk_level: 'Dusuk',
  },
  {
    id: 'stu-802',
    student_number: '802',
    first_name: 'Elif',
    last_name: 'Şahin',
    birth_date: '2012-06-18',
    gender: 'Kız',
    education_type: 'gunduzlu',
    class_id: 'cls-8a',
    class_name: '8-A',
    status: 'aktif',
    registration_date: '2026-08-21',
    parent_id: 'par-2',
    parent_name: 'Fatma Şahin',
    parent_phone: '0533 444 7788',
    parent_email: 'fatma.sahin@gmail.com',
    parent_relation: 'Anne',
    attendance_rate: 94.0,
    curriculum_rate: 78.0,
    absenteeism_count: 2,
    late_count: 1,
    excused_count: 0,
    risk_level: 'Dusuk',
  },
  {
    id: 'stu-803',
    student_number: '803',
    first_name: 'Baran',
    last_name: 'Öztürk',
    birth_date: '2012-01-25',
    gender: 'Erkek',
    education_type: 'yatili',
    class_id: 'cls-8a',
    class_name: '8-A',
    status: 'aktif',
    registration_date: '2026-08-22',
    parent_id: 'par-3',
    parent_name: 'Ali Öztürk',
    parent_phone: '0533 222 9900',
    parent_email: 'ali.ozturk@gmail.com',
    parent_relation: 'Baba',
    attendance_rate: 86.5,
    curriculum_rate: 65.0,
    absenteeism_count: 4,
    late_count: 2,
    excused_count: 1,
    risk_level: 'Yuksek', // Risk alarmı için
  },
  {
    id: 'stu-804',
    student_number: '804',
    first_name: 'Zeynep',
    last_name: 'Korkmaz',
    birth_date: '2012-09-03',
    gender: 'Kız',
    education_type: 'gunduzlu',
    class_id: 'cls-8a',
    class_name: '8-A',
    status: 'aktif',
    registration_date: '2026-08-22',
    parent_name: 'Hülya Korkmaz',
    parent_phone: '0533 666 1122',
    parent_email: 'hulya@gmail.com',
    parent_relation: 'Anne',
    attendance_rate: 98.0,
    curriculum_rate: 90.0,
    absenteeism_count: 0,
    late_count: 1,
    excused_count: 0,
    risk_level: 'Dusuk',
  },
  {
    id: 'stu-805',
    student_number: '805',
    first_name: 'Emir',
    last_name: 'Aydın',
    birth_date: '2012-03-14',
    gender: 'Erkek',
    education_type: 'gunduzlu',
    class_id: 'cls-8a',
    class_name: '8-A',
    status: 'aktif',
    registration_date: '2026-08-23',
    parent_name: 'Murat Aydın',
    parent_phone: '0533 777 3344',
    parent_email: 'murat.aydin@gmail.com',
    parent_relation: 'Baba',
    attendance_rate: 92.0,
    curriculum_rate: 75.0,
    absenteeism_count: 2,
    late_count: 0,
    excused_count: 1,
    risk_level: 'Dusuk',
  },
  {
    id: 'stu-806',
    student_number: '806',
    first_name: 'Ceren',
    last_name: 'Yıldız',
    birth_date: '2012-08-29',
    gender: 'Kız',
    education_type: 'gunduzlu',
    class_id: 'cls-8a',
    class_name: '8-A',
    status: 'aktif',
    registration_date: '2026-08-24',
    parent_name: 'Semra Yıldız',
    parent_phone: '0533 888 4455',
    parent_email: 'semra@gmail.com',
    parent_relation: 'Anne',
    attendance_rate: 95.0,
    curriculum_rate: 80.0,
    absenteeism_count: 1,
    late_count: 0,
    excused_count: 0,
    risk_level: 'Dusuk',
  },
  {
    id: 'stu-807',
    student_number: '807',
    first_name: 'Kaan',
    last_name: 'Erdoğan',
    birth_date: '2012-02-17',
    gender: 'Erkek',
    education_type: 'yatili',
    class_id: 'cls-8a',
    class_name: '8-A',
    status: 'aktif',
    registration_date: '2026-08-24',
    parent_name: 'Kemal Erdoğan',
    parent_phone: '0533 999 5566',
    parent_email: 'kemal.erd@gmail.com',
    parent_relation: 'Baba',
    attendance_rate: 91.0,
    curriculum_rate: 74.0,
    absenteeism_count: 2,
    late_count: 1,
    excused_count: 1,
    risk_level: 'Dusuk',
  },
  {
    id: 'stu-808',
    student_number: '808',
    first_name: 'Duru',
    last_name: 'Güneş',
    birth_date: '2012-11-05',
    gender: 'Kız',
    education_type: 'gunduzlu',
    class_id: 'cls-8a',
    class_name: '8-A',
    status: 'aktif',
    registration_date: '2026-08-25',
    parent_name: 'Aylin Güneş',
    parent_phone: '0533 111 6677',
    parent_email: 'aylin.gunes@gmail.com',
    parent_relation: 'Anne',
    attendance_rate: 97.0,
    curriculum_rate: 88.0,
    absenteeism_count: 1,
    late_count: 0,
    excused_count: 0,
    risk_level: 'Dusuk',
  },
  {
    id: 'stu-809',
    student_number: '809',
    first_name: 'Umut',
    last_name: 'Koç',
    birth_date: '2012-07-22',
    gender: 'Erkek',
    education_type: 'gunduzlu',
    class_id: 'cls-8a',
    class_name: '8-A',
    status: 'aktif',
    registration_date: '2026-08-25',
    parent_name: 'Sinan Koç',
    parent_phone: '0533 222 7788',
    parent_email: 'sinan.koc@gmail.com',
    parent_relation: 'Baba',
    attendance_rate: 93.5,
    curriculum_rate: 79.0,
    absenteeism_count: 2,
    late_count: 0,
    excused_count: 0,
    risk_level: 'Dusuk',
  },
  {
    id: 'stu-810',
    student_number: '810',
    first_name: 'İpek',
    last_name: 'Arslan',
    birth_date: '2012-05-19',
    gender: 'Kız',
    education_type: 'gunduzlu',
    class_id: 'cls-8a',
    class_name: '8-A',
    status: 'aktif',
    registration_date: '2026-08-26',
    parent_name: 'Gamze Arslan',
    parent_phone: '0533 333 8899',
    parent_email: 'gamze.arslan@gmail.com',
    parent_relation: 'Anne',
    attendance_rate: 99.0,
    curriculum_rate: 92.0,
    absenteeism_count: 0,
    late_count: 0,
    excused_count: 1,
    risk_level: 'Dusuk',
  },

  // 8-B Öğrencileri
  {
    id: 'stu-811',
    student_number: '811',
    first_name: 'Defne',
    last_name: 'Çelik',
    birth_date: '2012-04-12',
    gender: 'Kız',
    education_type: 'gunduzlu',
    class_id: 'cls-8b',
    class_name: '8-B',
    status: 'aktif',
    registration_date: '2026-08-20',
    parent_id: 'par-1', // Mustafa Çelik'in 2. çocuğu!
    parent_name: 'Mustafa Çelik',
    parent_phone: '0533 555 6677',
    parent_email: 'mustafa.celik@gmail.com',
    parent_relation: 'Baba',
    attendance_rate: 95.0,
    curriculum_rate: 80.0,
    absenteeism_count: 1,
    late_count: 1,
    excused_count: 0,
    risk_level: 'Dusuk',
  },
  {
    id: 'stu-812',
    student_number: '812',
    first_name: 'Alp',
    last_name: 'Bulut',
    birth_date: '2012-10-10',
    gender: 'Erkek',
    education_type: 'gunduzlu',
    class_id: 'cls-8b',
    class_name: '8-B',
    status: 'aktif',
    registration_date: '2026-08-21',
    parent_name: 'Tarkan Bulut',
    parent_phone: '0533 444 9900',
    parent_email: 'tarkan.bulut@gmail.com',
    parent_relation: 'Baba',
    attendance_rate: 88.0,
    curriculum_rate: 70.0,
    absenteeism_count: 4,
    late_count: 1,
    excused_count: 0,
    risk_level: 'Yuksek', // Devamsızlık uyarısı
  },
  {
    id: 'stu-813',
    student_number: '813',
    first_name: 'Merve',
    last_name: 'Polat',
    birth_date: '2012-01-15',
    gender: 'Kız',
    education_type: 'yatili',
    class_id: 'cls-8b',
    class_name: '8-B',
    status: 'aktif',
    registration_date: '2026-08-22',
    parent_name: 'Banu Polat',
    parent_phone: '0533 555 1100',
    parent_email: 'banu.polat@gmail.com',
    parent_relation: 'Anne',
    attendance_rate: 93.0,
    curriculum_rate: 77.0,
    absenteeism_count: 2,
    late_count: 0,
    excused_count: 1,
    risk_level: 'Dusuk',
  },
  {
    id: 'stu-814',
    student_number: '814',
    first_name: 'Can',
    last_name: 'Özer',
    birth_date: '2012-06-30',
    gender: 'Erkek',
    education_type: 'gunduzlu',
    class_id: 'cls-8b',
    class_name: '8-B',
    status: 'aktif',
    registration_date: '2026-08-23',
    parent_name: 'Fikret Özer',
    parent_phone: '0533 666 2211',
    parent_email: 'fikret.ozer@gmail.com',
    parent_relation: 'Baba',
    attendance_rate: 91.5,
    curriculum_rate: 74.0,
    absenteeism_count: 2,
    late_count: 2,
    excused_count: 0,
    risk_level: 'Dusuk',
  },
  {
    id: 'stu-815',
    student_number: '815',
    first_name: 'Selin',
    last_name: 'Tekin',
    birth_date: '2012-12-04',
    gender: 'Kız',
    education_type: 'gunduzlu',
    class_id: 'cls-8b',
    class_name: '8-B',
    status: 'aktif',
    registration_date: '2026-08-23',
    parent_name: 'Derya Tekin',
    parent_phone: '0533 777 3322',
    parent_email: 'derya.tekin@gmail.com',
    parent_relation: 'Anne',
    attendance_rate: 96.5,
    curriculum_rate: 85.0,
    absenteeism_count: 1,
    late_count: 0,
    excused_count: 0,
    risk_level: 'Dusuk',
  },
  {
    id: 'stu-816',
    student_number: '816',
    first_name: 'Burak',
    last_name: 'Kaya',
    birth_date: '2012-02-09',
    gender: 'Erkek',
    education_type: 'gunduzlu',
    class_id: 'cls-8b',
    class_name: '8-B',
    status: 'aktif',
    registration_date: '2026-08-24',
    parent_name: 'Serkan Kaya',
    parent_phone: '0533 888 4433',
    parent_email: 'serkan.kaya@gmail.com',
    parent_relation: 'Baba',
    attendance_rate: 90.0,
    curriculum_rate: 72.0,
    absenteeism_count: 3,
    late_count: 1,
    excused_count: 0,
    risk_level: 'Orta',
  },
  {
    id: 'stu-817',
    student_number: '817',
    first_name: 'Nehir',
    last_name: 'Çakır',
    birth_date: '2012-07-14',
    gender: 'Kız',
    education_type: 'gunduzlu',
    class_id: 'cls-8b',
    class_name: '8-B',
    status: 'aktif',
    registration_date: '2026-08-25',
    parent_name: 'Meltem Çakır',
    parent_phone: '0533 999 5544',
    parent_email: 'meltem.cakir@gmail.com',
    parent_relation: 'Anne',
    attendance_rate: 97.5,
    curriculum_rate: 89.0,
    absenteeism_count: 1,
    late_count: 0,
    excused_count: 1,
    risk_level: 'Dusuk',
  },
  {
    id: 'stu-818',
    student_number: '818',
    first_name: 'Ege',
    last_name: 'Vural',
    birth_date: '2012-03-22',
    gender: 'Erkek',
    education_type: 'yatili',
    class_id: 'cls-8b',
    class_name: '8-B',
    status: 'aktif',
    registration_date: '2026-08-25',
    parent_name: 'Levent Vural',
    parent_phone: '0533 111 6655',
    parent_email: 'levent.vural@gmail.com',
    parent_relation: 'Baba',
    attendance_rate: 92.0,
    curriculum_rate: 75.0,
    absenteeism_count: 2,
    late_count: 1,
    excused_count: 0,
    risk_level: 'Dusuk',
  },
  {
    id: 'stu-819',
    student_number: '819',
    first_name: 'Ada',
    last_name: 'Sezgin',
    birth_date: '2012-09-17',
    gender: 'Kız',
    education_type: 'gunduzlu',
    class_id: 'cls-8b',
    class_name: '8-B',
    status: 'aktif',
    registration_date: '2026-08-26',
    parent_name: 'Gülşah Sezgin',
    parent_phone: '0533 222 7766',
    parent_email: 'gulsah.sezgin@gmail.com',
    parent_relation: 'Anne',
    attendance_rate: 95.5,
    curriculum_rate: 82.0,
    absenteeism_count: 1,
    late_count: 0,
    excused_count: 0,
    risk_level: 'Dusuk',
  },
  {
    id: 'stu-820',
    student_number: '820',
    first_name: 'Yiğit',
    last_name: 'Kılıç',
    birth_date: '2012-05-02',
    gender: 'Erkek',
    education_type: 'gunduzlu',
    class_id: 'cls-8b',
    class_name: '8-B',
    status: 'aktif',
    registration_date: '2026-08-26',
    parent_name: 'Okan Kılıç',
    parent_phone: '0533 333 8877',
    parent_email: 'okan.kilic@gmail.com',
    parent_relation: 'Baba',
    attendance_rate: 94.0,
    curriculum_rate: 76.0,
    absenteeism_count: 2,
    late_count: 0,
    excused_count: 0,
    risk_level: 'Dusuk',
  },
];

export const initialSubjects: Subject[] = [
  {
    id: 'sub-mat',
    name: 'Matematik',
    code: 'MAT8',
    grade_level: 8,
    color: '#059669',
    weekly_hours: 5,
  },
  {
    id: 'sub-fen',
    name: 'Fen Bilimleri',
    code: 'FEN8',
    grade_level: 8,
    color: '#0d9488',
    weekly_hours: 4,
  },
  {
    id: 'sub-tur',
    name: 'Türkçe',
    code: 'TUR8',
    grade_level: 8,
    color: '#16a34a',
    weekly_hours: 5,
  },
];

export const initialCurriculums: Curriculum[] = [
  {
    id: 'curr-mat-8',
    name: '2026-2027 8. Sınıf Matematik Müfredatı',
    subject_id: 'sub-mat',
    subject_name: 'Matematik',
    grade_level: 8,
    academic_year_id: 'ay-2026-2027',
    version: 'v1.0',
    is_archived: false,
    units: [
      {
        id: 'unit-mat-1',
        curriculum_id: 'curr-mat-8',
        title: '1. Ünite: Çarpanlar ve Katlar',
        order_index: 1,
        topics: [
          {
            id: 'top-mat-101',
            unit_id: 'unit-mat-1',
            title: 'Pozitif Tam Sayıların Asal Çarpanları',
            description: 'Asal çarpan ağacı ve algoritma yöntemi',
            order_index: 1,
            estimated_hours: 4,
          },
          {
            id: 'top-mat-102',
            unit_id: 'unit-mat-1',
            title: 'EBOB ve EKOK Hesaplamaları & Problemleri',
            description: 'En büyük ortak bölen ve ortak kat uygulamaları',
            order_index: 2,
            estimated_hours: 6,
          },
          {
            id: 'top-mat-103',
            unit_id: 'unit-mat-1',
            title: 'Aralarında Asal Sayılar',
            description: 'Aralarında asal sayıların özellikleri',
            order_index: 3,
            estimated_hours: 3,
          },
        ],
      },
      {
        id: 'unit-mat-2',
        curriculum_id: 'curr-mat-8',
        title: '2. Ünite: Üslü ve Kareköklü İfadeler',
        order_index: 2,
        topics: [
          {
            id: 'top-mat-201',
            unit_id: 'unit-mat-2',
            title: 'Tam Sayıların Tam Sayı Kuvvetleri (Negatif Üs)',
            description: 'Üslü sayılarda negatif kuvvet ve çarpma kuralı',
            order_index: 1,
            estimated_hours: 5,
          },
          {
            id: 'top-mat-202',
            unit_id: 'unit-mat-2',
            title: 'Üslü İfadelerle Temel İşlemler & Bilimsel Gösterim',
            description: 'Çarpma, bölme ve çok büyük/küçük sayı gösterimi',
            order_index: 2,
            estimated_hours: 6,
          },
          {
            id: 'top-mat-203',
            unit_id: 'unit-mat-2',
            title: 'Tam Kare Sayılar ve Karekök Kavramı',
            description: 'Karekökün geometrik anlamı ve tahmin',
            order_index: 3,
            estimated_hours: 5,
          },
        ],
      },
      {
        id: 'unit-mat-3',
        curriculum_id: 'curr-mat-8',
        title: '3. Ünite: Olasılık ve Veri Analizi',
        order_index: 3,
        topics: [
          {
            id: 'top-mat-301',
            unit_id: 'unit-mat-3',
            title: 'Basit Olayların Olma Olasılığı',
            description: 'Eşit olasılıklı olaylar ve olasılık değeri hesabı',
            order_index: 1,
            estimated_hours: 5,
          },
          {
            id: 'top-mat-302',
            unit_id: 'unit-mat-3',
            title: 'Çizgi, Sütun ve Daire Grafikleri ile Veri Analizi',
            description: 'Grafik dönüştürme ve yorumlama',
            order_index: 2,
            estimated_hours: 4,
          },
        ],
      },
    ],
  },
  {
    id: 'curr-fen-8',
    name: '2026-2027 8. Sınıf Fen Bilimleri Müfredatı',
    subject_id: 'sub-fen',
    subject_name: 'Fen Bilimleri',
    grade_level: 8,
    academic_year_id: 'ay-2026-2027',
    version: 'v1.0',
    is_archived: false,
    units: [
      {
        id: 'unit-fen-1',
        curriculum_id: 'curr-fen-8',
        title: '1. Ünite: Mevsimler ve İklim',
        order_index: 1,
        topics: [
          {
            id: 'top-fen-101',
            unit_id: 'unit-fen-1',
            title: 'Mevsimlerin Oluşumu ve Dünya Ekseni',
            description: 'Eksen eğikliği ve Güneş ışınlarının geliş açısı',
            order_index: 1,
            estimated_hours: 5,
          },
          {
            id: 'top-fen-102',
            unit_id: 'unit-fen-1',
            title: 'İklim ve Hava Hareketleri',
            description: 'Rüzgar, nem, basınç alanları ve küresel iklim değişimi',
            order_index: 2,
            estimated_hours: 5,
          },
        ],
      },
      {
        id: 'unit-fen-2',
        curriculum_id: 'curr-fen-8',
        title: '2. Ünite: DNA ve Genetik Kod',
        order_index: 2,
        topics: [
          {
            id: 'top-fen-201',
            unit_id: 'unit-fen-2',
            title: 'DNA’nın Yapısı ve Kendini Eşlemesi',
            description: 'Nükleotitler, gen ve kromozom ilişkisi',
            order_index: 1,
            estimated_hours: 6,
          },
          {
            id: 'top-fen-202',
            unit_id: 'unit-fen-2',
            title: 'Kalıtım ve Mendel Çaprazlamaları',
            description: 'Alel genler, fenotip, genotip ve akraba evliliği',
            order_index: 2,
            estimated_hours: 6,
          },
          {
            id: 'top-fen-203',
            unit_id: 'unit-fen-2',
            title: 'Mutasyon, Modifikasyon ve Adaptasyon',
            description: 'Çevresel faktörlerin genetik mekanizmalara etkisi',
            order_index: 3,
            estimated_hours: 4,
          },
        ],
      },
    ],
  },
  {
    id: 'curr-tur-8',
    name: '2026-2027 8. Sınıf Türkçe Müfredatı',
    subject_id: 'sub-tur',
    subject_name: 'Türkçe',
    grade_level: 8,
    academic_year_id: 'ay-2026-2027',
    version: 'v1.0',
    is_archived: false,
    units: [
      {
        id: 'unit-tur-1',
        curriculum_id: 'curr-tur-8',
        title: '1. Ünite: Fiilimsiler (Eylemsiler)',
        order_index: 1,
        topics: [
          {
            id: 'top-tur-101',
            unit_id: 'unit-tur-1',
            title: 'İsim-Fiil, Sıfat-Fiil ve Zarf-Fiil',
            description: 'Fiilimsi ekleri ve cümledeki işlevleri',
            order_index: 1,
            estimated_hours: 8,
          },
          {
            id: 'top-tur-102',
            unit_id: 'unit-tur-1',
            title: 'Sözcükte Anlam ve Mantık Muhakeme',
            description: 'Mecaz, terim anlam ve paragrafta yapı',
            order_index: 2,
            estimated_hours: 6,
          },
        ],
      },
    ],
  },
];

// Topic Progress for 8-A and 8-B
export const initialTopicProgress: TopicProgress[] = [
  // 8-A Matematik
  {
    id: 'prog-1',
    class_curriculum_id: 'cc-8a-mat',
    topic_id: 'top-mat-101',
    status: 'tamamlandi',
    started_at: '2026-09-08',
    completed_at: '2026-09-18',
    teacher_notes: 'Tüm öğrenciler asal çarpan algoritmasını kavradı.',
    updated_by: 'prof-teacher-1',
    updated_at: '2026-09-18',
  },
  {
    id: 'prog-2',
    class_curriculum_id: 'cc-8a-mat',
    topic_id: 'top-mat-102',
    status: 'tamamlandi',
    started_at: '2026-09-19',
    completed_at: '2026-09-29',
    teacher_notes: 'EBOB-EKOK problemleri çözüldü, yeni nesil sorular tarandı.',
    updated_by: 'prof-teacher-1',
    updated_at: '2026-09-29',
  },
  {
    id: 'prog-3',
    class_curriculum_id: 'cc-8a-mat',
    topic_id: 'top-mat-103',
    status: 'tamamlandi',
    started_at: '2026-09-30',
    completed_at: '2026-10-03',
    teacher_notes: 'Aralarında asallık pekiştirildi.',
    updated_by: 'prof-teacher-1',
    updated_at: '2026-10-03',
  },
  {
    id: 'prog-4',
    class_curriculum_id: 'cc-8a-mat',
    topic_id: 'top-mat-201',
    status: 'devam_ediyor',
    started_at: '2026-10-04',
    teacher_notes: 'Negatif üs kuralı anlatıldı, alıştırmalar devam ediyor.',
    updated_by: 'prof-teacher-1',
    updated_at: '2026-10-06',
  },
  {
    id: 'prog-5',
    class_curriculum_id: 'cc-8a-mat',
    topic_id: 'top-mat-202',
    status: 'baslamadi',
  },
  {
    id: 'prog-6',
    class_curriculum_id: 'cc-8a-mat',
    topic_id: 'top-mat-203',
    status: 'baslamadi',
  },
  {
    id: 'prog-7',
    class_curriculum_id: 'cc-8a-mat',
    topic_id: 'top-mat-301',
    status: 'baslamadi',
  },
  {
    id: 'prog-8',
    class_curriculum_id: 'cc-8a-mat',
    topic_id: 'top-mat-302',
    status: 'baslamadi',
  },

  // 8-A Fen Bilimleri
  {
    id: 'prog-fen-1',
    class_curriculum_id: 'cc-8a-fen',
    topic_id: 'top-fen-101',
    status: 'tamamlandi',
    started_at: '2026-09-08',
    completed_at: '2026-09-22',
    teacher_notes: 'Mevsimler ünitesi modellemelerle tamamlandı.',
    updated_by: 'prof-teacher-2',
    updated_at: '2026-09-22',
  },
  {
    id: 'prog-fen-2',
    class_curriculum_id: 'cc-8a-fen',
    topic_id: 'top-fen-102',
    status: 'tamamlandi',
    started_at: '2026-09-23',
    completed_at: '2026-10-02',
    teacher_notes: 'İklim ve rüzgar deneyleri yapıldı.',
    updated_by: 'prof-teacher-2',
    updated_at: '2026-10-02',
  },
  {
    id: 'prog-fen-3',
    class_curriculum_id: 'cc-8a-fen',
    topic_id: 'top-fen-201',
    status: 'devam_ediyor',
    started_at: '2026-10-05',
    teacher_notes: 'DNA sarmalı ve nükleotit dizilimi işleniyor.',
    updated_by: 'prof-teacher-2',
    updated_at: '2026-10-06',
  },
];

export const initialLessons: Lesson[] = [
  {
    id: 'les-today-1',
    class_id: 'cls-8a',
    class_name: '8-A',
    subject_id: 'sub-mat',
    subject_name: 'Matematik',
    teacher_id: 'teach-1',
    teacher_name: 'Ayşe Yılmaz',
    topic_id: 'top-mat-201',
    topic_name: 'Tam Sayıların Tam Sayı Kuvvetleri (Negatif Üs)',
    lesson_date: '2026-10-07',
    start_time: '09:00',
    end_time: '09:40',
    status: 'tamamlandi',
    is_attendance_locked: true,
    notes: 'Negatif üs kuralı ve pay-payda yer değiştirme işlendi.',
  },
  {
    id: 'les-today-2',
    class_id: 'cls-8a',
    class_name: '8-A',
    subject_id: 'sub-mat',
    subject_name: 'Matematik',
    teacher_id: 'teach-1',
    teacher_name: 'Ayşe Yılmaz',
    topic_id: 'top-mat-201',
    topic_name: 'Negatif Üs Alıştırmaları & Problem Çözümü',
    lesson_date: '2026-10-07',
    start_time: '09:50',
    end_time: '10:30',
    status: 'tamamlandi',
    is_attendance_locked: true,
    notes: 'Örnek soru çözümü yapıldı.',
  },
  {
    id: 'les-today-3',
    class_id: 'cls-8a',
    class_name: '8-A',
    subject_id: 'sub-fen',
    subject_name: 'Fen Bilimleri',
    teacher_id: 'teach-2',
    teacher_name: 'Mehmet Demir',
    topic_id: 'top-fen-201',
    topic_name: 'DNA’nın Yapısı ve Kendini Eşlemesi',
    lesson_date: '2026-10-07',
    start_time: '11:20',
    end_time: '12:00',
    status: 'planlandi',
    is_attendance_locked: false,
    notes: 'DNA molekül modeli sınıfta incelenecek.',
  },
  {
    id: 'les-today-4',
    class_id: 'cls-8b',
    class_name: '8-B',
    subject_id: 'sub-mat',
    subject_name: 'Matematik',
    teacher_id: 'teach-1',
    teacher_name: 'Ayşe Yılmaz',
    topic_id: 'top-mat-103',
    topic_name: 'Aralarında Asal Sayılar Değerlendirme',
    lesson_date: '2026-10-07',
    start_time: '13:30',
    end_time: '14:10',
    status: 'planlandi',
    is_attendance_locked: false,
  },
  // Geçmiş dersler (Yoklama geçmişi için)
  {
    id: 'les-past-1',
    class_id: 'cls-8a',
    class_name: '8-A',
    subject_id: 'sub-mat',
    subject_name: 'Matematik',
    teacher_id: 'teach-1',
    teacher_name: 'Ayşe Yılmaz',
    topic_id: 'top-mat-103',
    topic_name: 'Aralarında Asal Sayılar',
    lesson_date: '2026-10-06',
    start_time: '09:00',
    end_time: '09:40',
    status: 'tamamlandi',
    is_attendance_locked: true,
  },
  {
    id: 'les-past-2',
    class_id: 'cls-8a',
    class_name: '8-A',
    subject_id: 'sub-mat',
    subject_name: 'Matematik',
    teacher_id: 'teach-1',
    teacher_name: 'Ayşe Yılmaz',
    topic_id: 'top-mat-102',
    topic_name: 'EBOB-EKOK Problemleri',
    lesson_date: '2026-10-05',
    start_time: '09:00',
    end_time: '09:40',
    status: 'tamamlandi',
    is_attendance_locked: true,
  },
];

export const initialAttendance: AttendanceRecord[] = [
  // 2026-10-07 Bugünün 1. dersi (les-today-1)
  { id: 'att-1', lesson_id: 'les-today-1', student_id: 'stu-801', student_name: 'Kerem Çelik', student_number: '801', date: '2026-10-07', status: 'geldi' },
  { id: 'att-2', lesson_id: 'les-today-1', student_id: 'stu-802', student_name: 'Elif Şahin', student_number: '802', date: '2026-10-07', status: 'geldi' },
  { id: 'att-3', lesson_id: 'les-today-1', student_id: 'stu-803', student_name: 'Baran Öztürk', student_number: '803', date: '2026-10-07', status: 'gelmedi', note: 'Servisi kaçırdı' },
  { id: 'att-4', lesson_id: 'les-today-1', student_id: 'stu-804', student_name: 'Zeynep Korkmaz', student_number: '804', date: '2026-10-07', status: 'geldi' },
  { id: 'att-5', lesson_id: 'les-today-1', student_id: 'stu-805', student_name: 'Emir Aydın', student_number: '805', date: '2026-10-07', status: 'geldi' },
  { id: 'att-6', lesson_id: 'les-today-1', student_id: 'stu-806', student_name: 'Ceren Yıldız', student_number: '806', date: '2026-10-07', status: 'geldi' },
  { id: 'att-7', lesson_id: 'les-today-1', student_id: 'stu-807', student_name: 'Kaan Erdoğan', student_number: '807', date: '2026-10-07', status: 'gec', note: '10 dk geç girdi' },
  { id: 'att-8', lesson_id: 'les-today-1', student_id: 'stu-808', student_name: 'Duru Güneş', student_number: '808', date: '2026-10-07', status: 'geldi' },
  { id: 'att-9', lesson_id: 'les-today-1', student_id: 'stu-809', student_name: 'Umut Koç', student_number: '809', date: '2026-10-07', status: 'geldi' },
  { id: 'att-10', lesson_id: 'les-today-1', student_id: 'stu-810', student_name: 'İpek Arslan', student_number: '810', date: '2026-10-07', status: 'izinli', note: 'Diş randevusu' },

  // Dün 2026-10-06 (les-past-1)
  { id: 'att-11', lesson_id: 'les-past-1', student_id: 'stu-801', student_name: 'Kerem Çelik', student_number: '801', date: '2026-10-06', status: 'geldi' },
  { id: 'att-12', lesson_id: 'les-past-1', student_id: 'stu-802', student_name: 'Elif Şahin', student_number: '802', date: '2026-10-06', status: 'geldi' },
  { id: 'att-13', lesson_id: 'les-past-1', student_id: 'stu-803', student_name: 'Baran Öztürk', student_number: '803', date: '2026-10-06', status: 'geldi' },
  { id: 'att-14', lesson_id: 'les-past-1', student_id: 'stu-804', student_name: 'Zeynep Korkmaz', student_number: '804', date: '2026-10-06', status: 'geldi' },
  { id: 'att-15', lesson_id: 'les-past-1', student_id: 'stu-805', student_name: 'Emir Aydın', student_number: '805', date: '2026-10-06', status: 'geldi' },
  { id: 'att-16', lesson_id: 'les-past-1', student_id: 'stu-806', student_name: 'Ceren Yıldız', student_number: '806', date: '2026-10-06', status: 'geldi' },
  { id: 'att-17', lesson_id: 'les-past-1', student_id: 'stu-807', student_name: 'Kaan Erdoğan', student_number: '807', date: '2026-10-06', status: 'geldi' },
  { id: 'att-18', lesson_id: 'les-past-1', student_id: 'stu-808', student_name: 'Duru Güneş', student_number: '808', date: '2026-10-06', status: 'geldi' },
  { id: 'att-19', lesson_id: 'les-past-1', student_id: 'stu-809', student_name: 'Umut Koç', student_number: '809', date: '2026-10-06', status: 'geldi' },
  { id: 'att-20', lesson_id: 'les-past-1', student_id: 'stu-810', student_name: 'İpek Arslan', student_number: '810', date: '2026-10-06', status: 'geldi' },
];

export const initialNotifications: NotificationItem[] = [
  {
    id: 'notif-1',
    role_target: 'mudur',
    title: 'Devamsızlık Eşiği Uyarısı',
    message: '8-A sınıfından Baran Öztürk (%86.5) devamsızlık sınırına yaklaştı.',
    type: 'warning',
    is_read: false,
    created_at: '2026-10-07 08:30',
  },
  {
    id: 'notif-2',
    role_target: 'all',
    title: 'Yeni Müfredat Onaylandı',
    message: '2026-2027 8. Sınıf Fen Bilimleri Müfredatı sisteme tanımlandı ve sınıflara atandı.',
    type: 'success',
    is_read: false,
    created_at: '2026-10-06 15:45',
  },
  {
    id: 'notif-3',
    role_target: 'ogretmen',
    title: 'Haftalık Yoklama Kilitleme Hatırlatması',
    message: 'Bugünkü tüm derslerin yoklamalarının saat 16:30’a kadar sisteme girilmesi gerekmektedir.',
    type: 'info',
    is_read: true,
    created_at: '2026-10-06 09:00',
  },
  {
    id: 'notif-4',
    role_target: 'veli',
    title: 'Ders Katılım Bilgisi',
    message: 'Öğrenciniz Kerem Çelik bugünkü 09:00 Matematik dersine eksiksiz katılmıştır.',
    type: 'info',
    is_read: false,
    created_at: '2026-10-07 09:42',
  },
];

export const initialActivityLogs: ActivityLog[] = [
  {
    id: 'log-1',
    user_name: 'Dr. Selim Karahan',
    user_role: 'mudur',
    action: 'OGRENCI_KAYDI',
    target_entity: 'Öğrenci: İpek Arslan (No: 810)',
    details: 'Yeni öğrenci kaydı 8-A sınıfına yapıldı ve veli kaydıyla ilişkilendirildi.',
    created_at: '2026-10-06 14:20',
  },
  {
    id: 'log-2',
    user_name: 'Ayşe Yılmaz',
    user_role: 'ogretmen',
    action: 'YOKLAMA_KILITLENDI',
    target_entity: 'Ders: 8-A Matematik (09:00)',
    details: '10 öğrencinin yoklaması kaydedildi ve oturum kilitlendi (9 Geldi, 1 İzinli).',
    created_at: '2026-10-07 09:41',
  },
  {
    id: 'log-3',
    user_name: 'Ayşe Yılmaz',
    user_role: 'ogretmen',
    action: 'MUFREDAT_GUNCELLEME',
    target_entity: 'Konu: Aralarında Asal Sayılar',
    details: 'Konu durumu "Tamamlandı" olarak güncellendi ve pekiştirme notu eklendi.',
    created_at: '2026-10-03 16:10',
  },
  {
    id: 'log-4',
    user_name: 'Dr. Selim Karahan',
    user_role: 'mudur',
    action: 'MUFREDAT_ATAMA',
    target_entity: 'Müfredat: 8. Sınıf Fen Bilimleri → 8-B',
    details: '2026-2027 Fen Bilimleri müfredatı Mehmet Demir öğretmenine ve 8-B sınıfına atandı.',
    created_at: '2026-10-02 11:30',
  },
  {
    id: 'log-5',
    user_name: 'Dr. Selim Karahan',
    user_role: 'mudur',
    action: 'SINIF_OLUSTURULDU',
    target_entity: 'Sınıf: 7-A',
    details: '2026-2027 yılı için 7-A sınıfı 20 kontenjanla açıldı.',
    created_at: '2026-09-25 10:15',
  },
];
